apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tenant-b-100mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-b-100mi
  namespace: tenant-b-100mi
spec:
  limits:
  - max: # this section defines default limits
      memory: 100Mi
    type: Pod
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: tenant-b-100mi
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 150Mi
