apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
reclaimPolicy: Delete
allowVolumeExpansion: false
---
#I skip a bunch of important config here, let the defaults sort it out
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs
spec:
  storageClassName: aws-ebs
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/aws_ebs
  capacity:
    storage: 10Mi
